# Generated by Django 3.2.7 on 2021-10-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('programming', 'programming'), ('cyber security', 'security'), ('mathematics', 'mathematics'), ('physics', 'physics'), ('electronics', 'electronics'), ('other', 'other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.CharField(max_length=5000),
        ),
    ]
